name: my_ikimono_zukan
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  supabase_flutter: ^2.6.0

dev_dependencies:
  build_runner: ^2.4.12
  envied_generator: ^0.5.4+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
